# Apache Cassandra Website config

# Site settings
title: Apache Cassandra Website
description: > # this means to ignore newlines until "baseurl:"
    The Apache Cassandra database is the right choice when you need scalability and high availability without
    compromising performance. Linear scalability and proven fault-tolerance on commodity hardware or cloud
    infrastructure make it the perfect platform for mission-critical data. Cassandra's support for replicating across
    multiple datacenters is best-in-class, providing lower latency for your users and the peace of mind of knowing that
    you can survive regional outages.
baseurl: ""
url: "http://cassandra.apache.org"
twitter_username: cassandra

destination: ../publish

exclude: [ Makefile, README ]


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
